version: '3'
services:
  app:
    build: .
    # image: php:8.2-fpm
    container_name: shop_app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - laravel

  nginx:
    image: nginx:latest
    container_name: shop_nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: mysql:8
    container_name: shop_db
    restart: always
    environment:
    #   MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: shop
      MYSQL_USER: user
    #   MYSQL_PASSWORD: secret
    ports:
      - "3312:3306"
    networks:
      - laravel

  frontend:
    build:
        context: ../frontend
    container_name: shop_react_app
    ports:
        - "3001:3000"
    networks:
        - laravel
    depends_on:
        - app
    volumes:
      - ../frontend:/app     # Nếu dùng volume để hot reload
    working_dir: /app
    command: npm start


networks:
  laravel:
